/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: calc.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "calc.pb-c.h"
void   request__init
                     (Request         *message)
{
  static const Request init_value = REQUEST__INIT;
  *message = init_value;
}
size_t request__get_packed_size
                     (const Request *message)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t request__pack
                     (const Request *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t request__pack_to_buffer
                     (const Request *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &request__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Request *
       request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Request *)
     protobuf_c_message_unpack (&request__descriptor,
                                allocator, len, data);
}
void   request__free_unpacked
                     (Request *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &request__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   reply__init
                     (Reply         *message)
{
  static const Reply init_value = REPLY__INIT;
  *message = init_value;
}
size_t reply__get_packed_size
                     (const Reply *message)
{
  assert(message->base.descriptor == &reply__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t reply__pack
                     (const Reply *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &reply__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t reply__pack_to_buffer
                     (const Reply *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &reply__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Reply *
       reply__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Reply *)
     protobuf_c_message_unpack (&reply__descriptor,
                                allocator, len, data);
}
void   reply__free_unpacked
                     (Reply *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &reply__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor request__field_descriptors[2] =
{
  {
    "a",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Request, a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "b",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(Request, b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned request__field_indices_by_name[] = {
  0,   /* field[0] = a */
  1,   /* field[1] = b */
};
static const ProtobufCIntRange request__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor request__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Request",
  "Request",
  "Request",
  "",
  sizeof(Request),
  2,
  request__field_descriptors,
  request__field_indices_by_name,
  1,  request__number_ranges,
  (ProtobufCMessageInit) request__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor reply__field_descriptors[1] =
{
  {
    "r",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_INT64,
    0,   /* quantifier_offset */
    offsetof(Reply, r),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned reply__field_indices_by_name[] = {
  0,   /* field[0] = r */
};
static const ProtobufCIntRange reply__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor reply__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Reply",
  "Reply",
  "Reply",
  "",
  sizeof(Reply),
  1,
  reply__field_descriptors,
  reply__field_indices_by_name,
  1,  reply__number_ranges,
  (ProtobufCMessageInit) reply__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCMethodDescriptor calc__method_descriptors[4] =
{
  { "Add", &request__descriptor, &reply__descriptor },
  { "Sub", &request__descriptor, &reply__descriptor },
  { "Mul", &request__descriptor, &reply__descriptor },
  { "Div", &request__descriptor, &reply__descriptor },
};
static const unsigned calc__method_indices_by_name[] = {
  0,        /* Add */
  3,        /* Div */
  2,        /* Mul */
  1         /* Sub */
};
const ProtobufCServiceDescriptor calc__descriptor =
{
  PROTOBUF_C__SERVICE_DESCRIPTOR_MAGIC,
  "Calc",
  "Calc",
  "Calc",
  "",
  4,
  calc__method_descriptors,
  calc__method_indices_by_name
};
void calc__add(ProtobufCService *service,
               const Request *input,
               Reply_Closure closure,
               void *closure_data)
{
  assert(service->descriptor == &calc__descriptor);
  service->invoke(service, 0, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void calc__sub(ProtobufCService *service,
               const Request *input,
               Reply_Closure closure,
               void *closure_data)
{
  assert(service->descriptor == &calc__descriptor);
  service->invoke(service, 1, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void calc__mul(ProtobufCService *service,
               const Request *input,
               Reply_Closure closure,
               void *closure_data)
{
  assert(service->descriptor == &calc__descriptor);
  service->invoke(service, 2, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void calc__div(ProtobufCService *service,
               const Request *input,
               Reply_Closure closure,
               void *closure_data)
{
  assert(service->descriptor == &calc__descriptor);
  service->invoke(service, 3, (const ProtobufCMessage *) input, (ProtobufCClosure) closure, closure_data);
}
void calc__init (Calc_Service *service,
                 Calc_ServiceDestroy destroy)
{
  protobuf_c_service_generated_init (&service->base,
                                     &calc__descriptor,
                                     (ProtobufCServiceDestroy) destroy);
}
